name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the cypress repo
        uses: actions/checkout@v3
        with:
          repository: NEETweeb/testGaCypress10
          path: app
          
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: yarn cy:allTests
          
#      - name: Install app dependencies
#        uses: bahmutov/npm-install@v1
#        with:
#          working-directory: app

#      - name: Start the application
#        run: |
#          cd app
#          npm run start &

#      - name: Run tests 🧪
#        # https://github.com/cypress-io/github-action
#        uses: cypress-io/github-action@v3 
          
